use_frameworks!

platform :ios, '9.0'

target 'LRSRACNetworking_Example' do
  pod 'LRSRACNetworking', :path => '../'

  target 'LRSRACNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
